### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by lrgeoemtry** [leewillis77/pay-with-ether#10]
Ive paid 2 months and we're just getting around to hooking this up. 
Is this a scam? 
Getting unauthorized key when its the actual key.

**Comment by leewillis77** [comment]
Hi; 

Sorry to hear that you're having problems. This repository is just for the technical WordPress plugin implementation. I don't have anything to do with the running of the paywithether.com paid-for service. 

If you're having problems with a paid-for key then I'd suggest reaching out to their support team using the form here and I'm sure they can sort things out:

https://www.paywithether.com/get-in-touch/
